export const MOVIE_SEARCH_START = 'MOVIE_SEARCH_START';
export const MOVIE_SEARCH_LOADING = 'MOVIE_SEARCH_LOADING';
export const MOVIE_SEARCH_SUCCESS = 'MOVIE_SEARCH_SUCCESS';
export const MOVIE_SEARCH_FAIL = 'MOVIE_SEARCH_FAIL';
